public class FindTheDifference {

    /*
    You are given two strings s and t.
    String t is generated by random shuffling string s and then add one more letter at a random position.
    Return the letter that was added to t.

    Constraints:
    0 <= s.length <= 1000
    t.length == s.length + 1
    s and t consist of lowercase English letters.
     */
    public char findTheDifference(String s, String t) {
        int len = s.length();
        if (len == 0) return t.charAt(0);

        int[] buckets = new int[26];
        for (int i = 0; i < len; i++) {
            buckets[s.charAt(i) - 'a']--;
            buckets[t.charAt(i) - 'a']++;
        }
        buckets[t.charAt(len) - 'a']++;

        for (int i = 0; i < 26; i++) {
            if (buckets[i] != 0) return (char) (i + 'a');
        }
        return ' '; //invalid on purpose
    }
}
